/**
 * #define 预处理器指令测试
 */

import { InnoScriptParser, InnoScriptGenerator } from "../src/index";

// 测试带有 #define 的 ISS 内容
const sampleIssWithDefines = `
; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

; 软件名称
#define MyAppName "Self Report"
; 软件版本
#define MyAppVersion "1.0.0"
; 发布者信息
#define MyAppPublisher "信息科技有限公司"
; 主程序可执行文件名
#define MyAppExeName "Self Report.exe"
; 文件关联显示名称
#define MyAppAssocName MyAppName + " File"
; 文件关联扩展名
#define MyAppAssocExt ".myp"
; 注册表Key
#define MyAppAssocKey StringChange(MyAppAssocName, " ", "") + MyAppAssocExt
; 快捷方式显示名称
#define MyAppShortcutName "自助接报"

[Setup]
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={autopf}\\{#MyAppName}
DefaultGroupName={#MyAppName}
OutputBaseFilename=myapp-setup
ChangesAssociations=yes

[Files]
Source: "{src}\\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs

[Icons]
Name: "{group}\\{#MyAppShortcutName}"; Filename: "{app}\\{#MyAppExeName}"
Name: "{autodesktop}\\{#MyAppShortcutName}"; Filename: "{app}\\{#MyAppExeName}"

[Registry]
Root: HKCR; Subkey: "{#MyAppAssocExt}"; ValueType: string; ValueName: ""; ValueData: "{#MyAppAssocKey}"; Flags: uninsdeletevalue
Root: HKCR; Subkey: "{#MyAppAssocKey}"; ValueType: string; ValueName: ""; ValueData: "{#MyAppAssocName}"; Flags: uninsdeletekey
Root: HKCR; Subkey: "{#MyAppAssocKey}\\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\\{#MyAppExeName},0"
Root: HKCR; Subkey: "{#MyAppAssocKey}\\shell\\open\\command"; ValueType: string; ValueName: ""; ValueData: "\\"{app}\\{#MyAppExeName}\\" \\"%1\\""
`;

console.log(
  "=== Test 1: Parse with preserveDefineReferences=true (保留 {#...} 引用) ==="
);
const configPreserved = InnoScriptParser.parse(sampleIssWithDefines, true);

console.log("\n1. Defines extracted:");
console.log(JSON.stringify(configPreserved.Defines, null, 2));

console.log("\n2. Setup section (with {#...} references preserved):");
console.log(JSON.stringify(configPreserved.Setup, null, 2));

console.log("\n3. Icons section (with {#...} references preserved):");
console.log(JSON.stringify(configPreserved.Icons, null, 2));

console.log(
  "\n=== Test 2: Generate script with #define (应该生成带 #define 和 {#...} 的脚本) ==="
);
const generator = new InnoScriptGenerator();
const generatedScript = generator.generate(configPreserved);

console.log("\nGenerated script:");
console.log(generatedScript);

console.log(
  "\n=== Test 3: Parse with preserveDefineReferences=false (替换 {#...} 为实际值) ==="
);
const configReplaced = InnoScriptParser.parse(sampleIssWithDefines, false);

console.log("\n1. Setup section (constants replaced):");
console.log(JSON.stringify(configReplaced.Setup, null, 2));

console.log("\n2. Icons section (constants replaced):");
console.log(JSON.stringify(configReplaced.Icons, null, 2));

console.log("\n✅ All #define tests passed!");

// 导出供外部使用
export { sampleIssWithDefines };
